# Generated by Django 5.2.12 on 2026-03-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=40, verbose_name='cores'),
        ),
    ]
